<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../WordTemplateBinding.Core/WordTemplateBinding.Core.csproj" />
    <PackageReference Include="DocumentFormat.OpenXml" />
    <PackageReference Include="MySqlConnector" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
